/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = 16
*/
module alex_encoder_29 (
    input [15:0] in,
    output reg [4:0] out
  );
  
  localparam WIDTH = 5'h10;
  
  
  integer i;
  
  always @* begin
    out = 1'h0;
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      if (in[(i)*1+0-:1]) begin
        out = i + 1'h1;
      end
    end
  end
endmodule
