/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pc_unit_9 (
    input clk,
    input rst,
    input [15:0] id,
    input [15:0] ra,
    input slow_clock,
    input [2:0] pcsel,
    output reg [15:0] ia,
    output reg [15:0] pc_4
  );
  
  
  
  reg [15:0] M_pc_d, M_pc_q = 1'h0;
  
  reg [15:0] internal_ia;
  
  reg [15:0] internal_pc_4;
  
  always @* begin
    M_pc_d = M_pc_q;
    
    ia = M_pc_q;
    pc_4 = M_pc_q + 3'h4;
    if (slow_clock) begin
      internal_ia = M_pc_q;
      internal_pc_4 = M_pc_q + 3'h4;
      
      case (pcsel)
        1'h0: begin
          M_pc_d = internal_pc_4;
        end
        1'h1: begin
          M_pc_d = internal_pc_4 + id * 3'h4;
        end
        2'h2: begin
          M_pc_d = {internal_ia[15+0-:1], ra[0+14-:15]};
        end
        2'h3: begin
          M_pc_d = 11'h500;
        end
        3'h4: begin
          M_pc_d = 11'h400;
        end
        default: begin
          M_pc_d = internal_pc_4;
        end
      endcase
      ia = internal_ia;
      pc_4 = {internal_ia[15+0-:1], internal_pc_4[0+14-:15]};
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_pc_q <= 1'h0;
    end else begin
      M_pc_q <= M_pc_d;
    end
  end
  
endmodule
