/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module answer_rom_2 (
    input [37:0] address,
    output reg [18:0] out
  );
  
  
  
  always @* begin
    
    case (address)
      38'h0000000000: begin
        out = 19'h00004;
      end
      38'h1fffc00000: begin
        out = 19'h3fff8;
      end
      38'h00001fffc0: begin
        out = 19'h3fff8;
      end
      38'h3fffc00000: begin
        out = 19'h7fff9;
      end
      38'h00003fffc0: begin
        out = 19'h7fff9;
      end
      38'h048d0d1580: begin
        out = 19'h23450;
      end
      38'h3e007e0800: begin
        out = 19'h78109;
      end
      38'h3780002b40: begin
        out = 19'h6f569;
      end
      38'h003bef8000: begin
        out = 19'h5f779;
      end
      38'h3fffffffc0: begin
        out = 19'h7fff1;
      end
      38'h1c001c0000: begin
        out = 19'h70003;
      end
      38'h3fffc00040: begin
        out = 19'h00004;
      end
      38'h0000000001: begin
        out = 19'h00004;
      end
      38'h1fffc00001: begin
        out = 19'h3fff8;
      end
      38'h00001fffc1: begin
        out = 19'h40009;
      end
      38'h3fffc00001: begin
        out = 19'h7fff9;
      end
      38'h00001fffc1: begin
        out = 19'h40009;
      end
      38'h1d95150c81: begin
        out = 19'h11110;
      end
      38'h150c9d9501: begin
        out = 19'h6eef1;
      end
      38'h3b72f72e81: begin
        out = 19'h08888;
      end
      38'h372ebb72c1: begin
        out = 19'h77779;
      end
      38'h1fffe00001: begin
        out = 19'h7fffb;
      end
      38'h20001fffc1: begin
        out = 19'h0000a;
      end
      38'h0000000004: begin
        out = 19'h00004;
      end
      38'h00001fffc4: begin
        out = 19'h00000;
      end
      38'h00003fffc4: begin
        out = 19'h00001;
      end
      38'h1fffc00004: begin
        out = 19'h00000;
      end
      38'h3fffc00004: begin
        out = 19'h00001;
      end
      38'h00014000c4: begin
        out = 19'h00078;
      end
      38'h00017fffc4: begin
        out = 19'h7ffd8;
      end
      38'h3fff800104: begin
        out = 19'h7ffc0;
      end
      38'h3fffbfff44: begin
        out = 19'h00031;
      end
      38'h1fffdc0004: begin
        out = 19'h48003;
      end
      38'h200023ffc4: begin
        out = 19'h40002;
      end
      38'h0000000010: begin
        out = 19'h00004;
      end
      38'h3fffffffd0: begin
        out = 19'h00001;
      end
      38'h3fffc00010: begin
        out = 19'h7fff9;
      end
      38'h15556aaa90: begin
        out = 19'h7fff9;
      end
      38'h3fffd55550: begin
        out = 19'h55550;
      end
      38'h0000000011: begin
        out = 19'h00004;
      end
      38'h3fffffffd1: begin
        out = 19'h7fffc;
      end
      38'h3fffc00011: begin
        out = 19'h00001;
      end
      38'h15556aaa91: begin
        out = 19'h00003;
      end
      38'h37ab403fd1: begin
        out = 19'h00569;
      end
      38'h0000000012: begin
        out = 19'h00004;
      end
      38'h3fffc00012: begin
        out = 19'h7fff9;
      end
      38'h2fbbc00012: begin
        out = 19'h5f779;
      end
      38'h048d2af352: begin
        out = 19'h091a1;
      end
      38'h0000000013: begin
        out = 19'h00004;
      end
      38'h3fffffffd3: begin
        out = 19'h7fffc;
      end
      38'h3fffc00013: begin
        out = 19'h7fff9;
      end
      38'h15556aaa93: begin
        out = 19'h7fffb;
      end
      38'h3780002b53: begin
        out = 19'h6f569;
      end
      38'h37ab400160: begin
        out = 19'h6ad01;
      end
      38'h37ab400220: begin
        out = 19'h56801;
      end
      38'h37ab4003e0: begin
        out = 19'h40001;
      end
      38'h37ab400161: begin
        out = 19'h037a9;
      end
      38'h37ab400221: begin
        out = 19'h006f1;
      end
      38'h37ab4003e1: begin
        out = 19'h00009;
      end
      38'h37ab400162: begin
        out = 19'h7f7a9;
      end
      38'h37ab400222: begin
        out = 19'h7fef1;
      end
      38'h37ab4003e2: begin
        out = 19'h7fff9;
      end
      38'h1f2ac00162: begin
        out = 19'h01f28;
      end
      38'h1f2ac00222: begin
        out = 19'h003e0;
      end
      38'h1f2ac003e2: begin
        out = 19'h00000;
      end
      38'h37ab400163: begin
        out = 19'h6add9;
      end
      38'h37ab400223: begin
        out = 19'h56ef1;
      end
      38'h37ab4003e3: begin
        out = 19'h77ab1;
      end
      38'h37ab400164: begin
        out = 19'h377a9;
      end
      38'h37ab400224: begin
        out = 19'h56ef1;
      end
      38'h37ab4003e4: begin
        out = 19'h5ead9;
      end
      38'h20003ffff3: begin
        out = 19'h00001;
      end
      38'h2000000033: begin
        out = 19'h00001;
      end
      38'h20001ffff3: begin
        out = 19'h00002;
      end
      38'h00001ffff3: begin
        out = 19'h00001;
      end
      38'h00005ffff3: begin
        out = 19'h00001;
      end
      38'h2000200033: begin
        out = 19'h0000c;
      end
      38'h0000000033: begin
        out = 19'h0000c;
      end
      38'h1fffdffff3: begin
        out = 19'h0000c;
      end
      38'h3fffe00033: begin
        out = 19'h00000;
      end
      38'h0000200033: begin
        out = 19'h00003;
      end
      38'h1fffe00033: begin
        out = 19'h00003;
      end
      38'h1fffc00033: begin
        out = 19'h00000;
      end
      38'h1fffc00073: begin
        out = 19'h00000;
      end
      38'h20003ffff5: begin
        out = 19'h00009;
      end
      38'h2000000035: begin
        out = 19'h00009;
      end
      38'h20001ffff5: begin
        out = 19'h0000a;
      end
      38'h00001ffff5: begin
        out = 19'h00009;
      end
      38'h00005ffff5: begin
        out = 19'h00009;
      end
      38'h2000200035: begin
        out = 19'h00004;
      end
      38'h0000000035: begin
        out = 19'h00004;
      end
      38'h1fffdffff5: begin
        out = 19'h00004;
      end
      38'h3fffe00035: begin
        out = 19'h00000;
      end
      38'h0000200035: begin
        out = 19'h00003;
      end
      38'h1fffe00035: begin
        out = 19'h00003;
      end
      38'h1fffc00035: begin
        out = 19'h00000;
      end
      38'h1fffc00075: begin
        out = 19'h00000;
      end
      38'h20003ffff7: begin
        out = 19'h00009;
      end
      38'h2000000037: begin
        out = 19'h00009;
      end
      38'h20001ffff7: begin
        out = 19'h0000a;
      end
      38'h00001ffff7: begin
        out = 19'h00009;
      end
      38'h00005ffff7: begin
        out = 19'h00009;
      end
      38'h2000200037: begin
        out = 19'h0000c;
      end
      38'h0000000037: begin
        out = 19'h0000c;
      end
      38'h1fffdffff7: begin
        out = 19'h0000c;
      end
      38'h3fffe00037: begin
        out = 19'h00000;
      end
      38'h0000200037: begin
        out = 19'h00003;
      end
      38'h1fffe00037: begin
        out = 19'h00003;
      end
      38'h1fffc00037: begin
        out = 19'h00000;
      end
      38'h1fffc00077: begin
        out = 19'h00000;
      end
      default: begin
        out = 19'h00000;
      end
    endcase
  end
endmodule
