/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     STATES = NUM_STATE_BITS
*/
module answer_fsm_6 (
    input clk,
    input rst,
    input [6:0] in,
    output reg [37:0] out
  );
  
  localparam STATES = 3'h7;
  
  
  localparam ADD_state = 4'd0;
  localparam SUB_state = 4'd1;
  localparam MULT_state = 4'd2;
  localparam XOR_state = 4'd3;
  localparam AND_state = 4'd4;
  localparam PASSTHROUGH_state = 4'd5;
  localparam OR_state = 4'd6;
  localparam SHL_state = 4'd7;
  localparam SHR_state = 4'd8;
  localparam SRA_state = 4'd9;
  localparam RTL_state = 4'd10;
  localparam RTR_state = 4'd11;
  localparam CMPEQ_state = 4'd12;
  localparam CMPLT_state = 4'd13;
  localparam CMPLE_state = 4'd14;
  
  reg [3:0] M_state_d, M_state_q = ADD_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    
    case (M_state_q)
      ADD_state: begin
        
        case (in)
          1'h1: begin
            out = 38'h0000000000;
          end
          2'h2: begin
            out = 38'h1fffc00000;
          end
          2'h3: begin
            out = 38'h00001fffc0;
          end
          3'h4: begin
            out = 38'h3fffc00000;
          end
          3'h5: begin
            out = 38'h00003fffc0;
          end
          3'h6: begin
            out = 38'h048d0d1580;
          end
          3'h7: begin
            out = 38'h3e007e0800;
          end
          4'h8: begin
            out = 38'h3780002b40;
          end
          4'h9: begin
            out = 38'h003bef8000;
          end
          4'ha: begin
            out = 38'h3fffffffc0;
          end
          4'hb: begin
            out = 38'h1c001c0000;
          end
          4'hc: begin
            out = 38'h3fffc00040;
            M_state_d = SUB_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      SUB_state: begin
        
        case (in)
          4'hd: begin
            out = 38'h0000000001;
          end
          4'he: begin
            out = 38'h1fffc00001;
          end
          4'hf: begin
            out = 38'h00001fffc1;
          end
          5'h10: begin
            out = 38'h3fffc00001;
          end
          5'h11: begin
            out = 38'h00001fffc1;
          end
          5'h12: begin
            out = 38'h1d95150c81;
          end
          5'h13: begin
            out = 38'h150c9d9501;
          end
          5'h14: begin
            out = 38'h3b72f72e81;
          end
          5'h15: begin
            out = 38'h372ebb72c1;
          end
          5'h16: begin
            out = 38'h1fffe00001;
          end
          5'h17: begin
            out = 38'h20001fffc1;
            M_state_d = MULT_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      MULT_state: begin
        
        case (in)
          5'h18: begin
            out = 38'h0000000004;
          end
          5'h19: begin
            out = 38'h00001fffc4;
          end
          5'h1a: begin
            out = 38'h00003fffc4;
          end
          5'h1b: begin
            out = 38'h1fffc00004;
          end
          5'h1c: begin
            out = 38'h3fffc00004;
          end
          5'h1d: begin
            out = 38'h00014000c4;
          end
          5'h1e: begin
            out = 38'h00017fffc4;
          end
          5'h1f: begin
            out = 38'h3fff800104;
          end
          6'h20: begin
            out = 38'h3fffbfff44;
          end
          6'h21: begin
            out = 38'h1fffdc0004;
          end
          6'h22: begin
            out = 38'h200023ffc4;
            M_state_d = XOR_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      XOR_state: begin
        
        case (in)
          6'h23: begin
            out = 38'h0000000010;
          end
          6'h24: begin
            out = 38'h3fffffffd0;
          end
          6'h25: begin
            out = 38'h3fffc00010;
          end
          6'h26: begin
            out = 38'h15556aaa90;
          end
          6'h27: begin
            out = 38'h3fffd55550;
            M_state_d = AND_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      AND_state: begin
        
        case (in)
          6'h28: begin
            out = 38'h0000000011;
          end
          6'h29: begin
            out = 38'h3fffffffd1;
          end
          6'h2a: begin
            out = 38'h3fffc00011;
          end
          6'h2b: begin
            out = 38'h15556aaa91;
          end
          6'h2c: begin
            out = 38'h37ab403fd1;
            M_state_d = PASSTHROUGH_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      PASSTHROUGH_state: begin
        
        case (in)
          6'h2d: begin
            out = 38'h0000000012;
          end
          6'h2e: begin
            out = 38'h3fffc00012;
          end
          6'h2f: begin
            out = 38'h2fbbc00012;
          end
          6'h30: begin
            out = 38'h048d2af352;
            M_state_d = OR_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      OR_state: begin
        
        case (in)
          6'h31: begin
            out = 38'h0000000013;
          end
          6'h32: begin
            out = 38'h3fffffffd3;
          end
          6'h33: begin
            out = 38'h3fffc00013;
          end
          6'h34: begin
            out = 38'h15556aaa93;
          end
          6'h35: begin
            out = 38'h3780002b53;
            M_state_d = SHL_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      SHL_state: begin
        
        case (in)
          6'h36: begin
            out = 38'h37ab400160;
          end
          6'h37: begin
            out = 38'h37ab400220;
          end
          6'h38: begin
            out = 38'h37ab4003e0;
            M_state_d = SHR_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      SHR_state: begin
        
        case (in)
          6'h39: begin
            out = 38'h37ab400161;
          end
          6'h3a: begin
            out = 38'h37ab400221;
          end
          6'h3b: begin
            out = 38'h37ab4003e1;
            M_state_d = SRA_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      SRA_state: begin
        
        case (in)
          6'h3c: begin
            out = 38'h37ab400162;
          end
          6'h3d: begin
            out = 38'h37ab400222;
          end
          6'h3e: begin
            out = 38'h37ab4003e2;
          end
          6'h3f: begin
            out = 38'h1f2ac00162;
          end
          7'h40: begin
            out = 38'h1f2ac00222;
          end
          7'h41: begin
            out = 38'h1f2ac003e2;
            M_state_d = RTL_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      RTL_state: begin
        
        case (in)
          7'h42: begin
            out = 38'h37ab400163;
          end
          7'h43: begin
            out = 38'h37ab400223;
          end
          7'h44: begin
            out = 38'h37ab4003e3;
            M_state_d = RTR_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      RTR_state: begin
        
        case (in)
          7'h45: begin
            out = 38'h37ab400164;
          end
          7'h46: begin
            out = 38'h37ab400224;
          end
          7'h47: begin
            out = 38'h37ab4003e4;
            M_state_d = CMPEQ_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      CMPEQ_state: begin
        
        case (in)
          7'h48: begin
            out = 38'h20003ffff3;
          end
          7'h49: begin
            out = 38'h2000000033;
          end
          7'h4a: begin
            out = 38'h20001ffff3;
          end
          7'h4b: begin
            out = 38'h00001ffff3;
          end
          7'h4c: begin
            out = 38'h00005ffff3;
          end
          7'h4d: begin
            out = 38'h2000200033;
          end
          7'h4e: begin
            out = 38'h0000000033;
          end
          7'h4f: begin
            out = 38'h1fffdffff3;
          end
          7'h50: begin
            out = 38'h3fffe00033;
          end
          7'h51: begin
            out = 38'h0000200033;
          end
          7'h52: begin
            out = 38'h1fffe00033;
          end
          7'h53: begin
            out = 38'h1fffc00033;
          end
          7'h54: begin
            out = 38'h1fffc00073;
            M_state_d = CMPLT_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      CMPLT_state: begin
        
        case (in)
          7'h55: begin
            out = 38'h20003ffff5;
          end
          7'h56: begin
            out = 38'h2000000035;
          end
          7'h57: begin
            out = 38'h20001ffff5;
          end
          7'h58: begin
            out = 38'h00001ffff5;
          end
          7'h59: begin
            out = 38'h00005ffff5;
          end
          7'h5a: begin
            out = 38'h2000200035;
          end
          7'h5b: begin
            out = 38'h0000000035;
          end
          7'h5c: begin
            out = 38'h1fffdffff5;
          end
          7'h5d: begin
            out = 38'h3fffe00035;
          end
          7'h5e: begin
            out = 38'h0000200035;
          end
          7'h5f: begin
            out = 38'h1fffe00035;
          end
          7'h60: begin
            out = 38'h1fffc00035;
          end
          7'h61: begin
            out = 38'h1fffc00075;
            M_state_d = CMPLE_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      CMPLE_state: begin
        
        case (in)
          7'h62: begin
            out = 38'h20003ffff7;
          end
          7'h63: begin
            out = 38'h2000000037;
          end
          7'h64: begin
            out = 38'h20001ffff7;
          end
          7'h65: begin
            out = 38'h00001ffff7;
          end
          7'h66: begin
            out = 38'h00005ffff7;
          end
          7'h67: begin
            out = 38'h2000200037;
          end
          7'h68: begin
            out = 38'h0000000037;
          end
          7'h69: begin
            out = 38'h1fffdffff7;
          end
          7'h6a: begin
            out = 38'h3fffe00037;
          end
          7'h6b: begin
            out = 38'h0000200037;
          end
          7'h6c: begin
            out = 38'h1fffe00037;
          end
          7'h6d: begin
            out = 38'h1fffc00037;
          end
          7'h6e: begin
            out = 38'h1fffc00077;
            M_state_d = ADD_state;
          end
          default: begin
            out = 38'h0000000000;
          end
        endcase
      end
      default: begin
        out = 38'h0000000000;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
