/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module answer_rom_2 (
    input [37:0] address,
    output reg [18:0] out
  );
  
  
  
  always @* begin
    
    case (address)
      1'h0: begin
        out = 7'h64;
      end
      120'hd5fe01dedf5cf85290616ecfc00000: begin
        out = 57'h18abef784607158;
      end
      67'h605f9f6dd18babfc0: begin
        out = 57'h18abef784607158;
      end
      124'h85bec12b4b9a3d15384980ecfc00000: begin
        out = 60'hf6b75ab2bc47159;
      end
      70'h3c3bc3a4a2f75abfc0: begin
        out = 60'hf6b75ab2bc47159;
      end
      113'h1ed87f9fa61b52951951dbd4c6b80: begin
        out = 57'h1634f7bd4bcfd50;
      end
      124'h85be698495cb31ea59343fbcb3ce800: begin
        out = 60'hf6b109d1f6b64e9;
      end
      124'h848a9a33bc0c4c06acd02f558897540: begin
        out = 60'hf47eea1375901c9;
      end
      97'h166b23d2269eef50badbd8000: begin
        out = 60'he08301b852af2d9;
      end
      124'h85bec12b4b9a40d8f483cb1c71abfc0: begin
        out = 60'hf6b75ab2bc46d71;
      end
      120'hd5c739ad3ddc5e1acff541945c0000: begin
        out = 60'hf67831e74af000b;
      end
      124'h85bec12b4b9a3d15384980ecfcf4240: begin
        out = 7'h64;
      end
      1'h1: begin
        out = 7'h64;
      end
      120'hd5fe01dedf5cf85290616ecfc00001: begin
        out = 57'h18abef784607158;
      end
      67'h605f9f6dd18babfc1: begin
        out = 60'hde0b6b3a76403f3;
      end
      124'h85bec12b4b9a3d15384980ecfc00001: begin
        out = 60'hf6b75ab2bc47159;
      end
      67'h605f9f6dd18babfc1: begin
        out = 60'hde0b6b3a76403f3;
      end
      120'hd5cca6330c97cf0d2670122c506281: begin
        out = 54'h2387db4a5c1810;
      end
      120'hc289c66b71cb73f47cd8919a0a5501: begin
        out = 60'hf47edcfe1687c7b;
      end
      124'h859fe8ababf425873f6fccac047cc81: begin
        out = 50'h38d95edd60272;
      end
      124'h848a9264ab6f559db019663b53792c1: begin
        out = 60'hf67e8153dee72d9;
      end
      120'hd5fe01dedf5d2e885a0f34ae600001: begin
        out = 60'hf6b75ab2bc47159;
      end
      123'h785ee10d5da46df06ee2d7d18babfc1: begin
        out = 10'h3e8;
      end
      7'h64: begin
        out = 7'h64;
      end
      67'h605f9f6dd18bac024: begin
        out = 1'h0;
      end
      70'h3c3bc3a4a2f75ac024: begin
        out = 1'h1;
      end
      120'hd5fe01dedf5cf85290616ecfc00064: begin
        out = 1'h0;
      end
      124'h85bec12b4b9a3d15384980ecfc00064: begin
        out = 1'h1;
      end
      80'hd5e035af96a853e7d924: begin
        out = 21'h10f3d8;
      end
      80'hd61c71733b4b4a9ac024: begin
        out = 60'hf6b75ab2bc2eab8;
      end
      124'h85bec12b4b9a1b339a3ce542375e164: begin
        out = 60'hf6b75ab2bc2bfc0;
      end
      124'h85bec12b4b9a1ef756772f7144229a4: begin
        out = 17'h1adb1;
      end
      120'hd5fe01dedf5cfe56ff9954641c0064: begin
        out = 60'hde444324c2a800b;
      end
      123'h785ee10d5da470f3848a35d62fec024: begin
        out = 60'hde0b6b3a764000a;
      end
      14'h2710: begin
        out = 7'h64;
      end
      124'h85bec12b4b9a40d8f483cb1c71ae6d0: begin
        out = 1'h1;
      end
      124'h85bec12b4b9a3d15384980ecfc02710: begin
        out = 60'hf6b75ab2bc47159;
      end
      120'hc289d327b3c949c98f5dacc5358f90: begin
        out = 60'hf6b75ab2bc47159;
      end
      124'h85bec12b4b9a3d6cd508fc089257e50: begin
        out = 60'he04998456557e50;
      end
      14'h2711: begin
        out = 7'h64;
      end
      124'h85bec12b4b9a40d8f483cb1c71ae6d1: begin
        out = 60'hf6b75ab2bc471c6;
      end
      124'h85bec12b4b9a3d15384980ecfc02711: begin
        out = 1'h1;
      end
      120'hc289d327b3c949c98f5dacc5358f91: begin
        out = 1'h1;
      end
      124'h848a9a482231e20c3d333d8a71326d1: begin
        out = 34'h25a1291c9;
      end
      14'h271a: begin
        out = 7'h64;
      end
      124'h85bec12b4b9a3d15384980ecfc0271a: begin
        out = 60'hf6b75ab2bc47159;
      end
      123'h79b5437997148187cfbfe41abc0271a: begin
        out = 60'he08301b852af2d9;
      end
      113'h1ed87f9fa61eb527e3c3dcd0a845a: begin
        out = 50'h38e677ffb8e21;
      end
      14'h271b: begin
        out = 7'h64;
      end
      124'h85bec12b4b9a40d8f483cb1c71ae6db: begin
        out = 60'hf6b75ab2bc471c6;
      end
      124'h85bec12b4b9a3d15384980ecfc0271b: begin
        out = 60'hf6b75ab2bc47159;
      end
      120'hc289d327b3c949c98f5dacc5358f9b: begin
        out = 60'hf6b75ab2bc47159;
      end
      124'h848a9a33bc0c4c06acd02f558899c5b: begin
        out = 60'hf47eea1375901c9;
      end
      124'h848a9a482231e20c3d329bdab46a9e0: begin
        out = 60'hf4792dc9a9fcd01;
      end
      124'h848a9a482231e20c3d329bde0dc50a0: begin
        out = 60'he04a1c8be88c801;
      end
      124'h848a9a482231e20c3d329bde77a0a60: begin
        out = 60'hde0b6b3a7640001;
      end
      124'h848a9a482231e20c3d329bdab46a9e1: begin
        out = 44'ha03b94e6009;
      end
      124'h848a9a482231e20c3d329bde0dc50a1: begin
        out = 34'h290503471;
      end
      124'h848a9a482231e20c3d329bde77a0a61: begin
        out = 10'h3e9;
      end
      124'h848a9a482231e20c3d329bdab46a9ea: begin
        out = 60'hf6b7593e33e2009;
      end
      124'h848a9a482231e20c3d329bde0dc50aa: begin
        out = 60'hf6b75ab25ce8c71;
      end
      124'h848a9a482231e20c3d329bde77a0a6a: begin
        out = 60'hf6b75ab2bc47159;
      end
      120'hd5fd76e751461214ce4c3c80c6a9ea: begin
        out = 41'h102b2ba1188;
      end
      120'hd5fd76e751461214ce4c3cb65c50aa: begin
        out = 31'h423a0a60;
      end
      120'hd5fd76e751461214ce4c3cbcfa0a6a: begin
        out = 1'h0;
      end
      124'h848a9a482231e20c3d329bdab46a9eb: begin
        out = 60'hf4792dc9b47d0b9;
      end
      124'h848a9a482231e20c3d329bde0dc50ab: begin
        out = 60'he04a1cb4ed8fc71;
      end
      124'h848a9a482231e20c3d329bde77a0a6b: begin
        out = 60'hf67e82a2cece631;
      end
      124'h848a9a482231e20c3d329bdab46aa44: begin
        out = 57'h18731619713a009;
      end
      124'h848a9a482231e20c3d329bde0dc5104: begin
        out = 60'he04a1cb4ed8fc71;
      end
      124'h848a9a482231e20c3d329bde77a0ac4: begin
        out = 60'he082f479f9215b9;
      end
      123'h785ee10d5da47153cb7db42f75c6d7b: begin
        out = 1'h1;
      end
      123'h785ee10d5da46d900f436a00001adbb: begin
        out = 1'h1;
      end
      123'h785ee10d5da46df06ee2d7d18bc6d7b: begin
        out = 1'h0;
      end
      67'h605f9f6dd18bc6d7b: begin
        out = 1'h1;
      end
      74'h2241fdac097cafc6d7b: begin
        out = 1'h1;
      end
      123'h785ee10d5da470f36bde465dea1adbb: begin
        out = 11'h456;
      end
      17'h1adbb: begin
        out = 11'h44c;
      end
      120'hd5fe01dedf5cfe588a584be87c6d7b: begin
        out = 11'h44c;
      end
      124'h85bec12b4b9a407894e45d4ae61adbb: begin
        out = 4'ha;
      end
      70'h3635c9adc5dea1adbb: begin
        out = 1'h1;
      end
      120'hd5fe01dedf5d2e885a0f34ae61adbb: begin
        out = 1'h1;
      end
      120'hd5fe01dedf5cf85290616ecfc1adbb: begin
        out = 1'h0;
      end
      120'hd5fe01dedf5cf85290616ecfd0effb: begin
        out = 1'h0;
      end
      123'h785ee10d5da47153cb7db42f75c6dd5: begin
        out = 10'h3e9;
      end
      123'h785ee10d5da46d900f436a00001ae15: begin
        out = 1'h1;
      end
      123'h785ee10d5da46df06ee2d7d18bc6dd5: begin
        out = 1'h0;
      end
      67'h605f9f6dd18bc6dd5: begin
        out = 10'h3e9;
      end
      74'h2241fdac097cafc6dd5: begin
        out = 10'h3e9;
      end
      123'h785ee10d5da470f36bde465dea1ae15: begin
        out = 7'h6e;
      end
      17'h1ae15: begin
        out = 7'h64;
      end
      120'hd5fe01dedf5cfe588a584be87c6dd5: begin
        out = 7'h64;
      end
      124'h85bec12b4b9a407894e45d4ae61ae15: begin
        out = 4'ha;
      end
      70'h3635c9adc5dea1ae15: begin
        out = 10'h3e9;
      end
      120'hd5fe01dedf5d2e885a0f34ae61ae15: begin
        out = 10'h3e9;
      end
      120'hd5fe01dedf5cf85290616ecfc1ae15: begin
        out = 1'h0;
      end
      120'hd5fe01dedf5cf85290616ecfd0f055: begin
        out = 1'h0;
      end
      123'h785ee10d5da47153cb7db42f75c6ddf: begin
        out = 10'h3e9;
      end
      123'h785ee10d5da46d900f436a00001ae1f: begin
        out = 1'h1;
      end
      123'h785ee10d5da46df06ee2d7d18bc6ddf: begin
        out = 1'h0;
      end
      67'h605f9f6dd18bc6ddf: begin
        out = 10'h3e9;
      end
      74'h2241fdac097cafc6ddf: begin
        out = 10'h3e9;
      end
      123'h785ee10d5da470f36bde465dea1ae1f: begin
        out = 11'h456;
      end
      17'h1ae1f: begin
        out = 11'h44c;
      end
      120'hd5fe01dedf5cfe588a584be87c6ddf: begin
        out = 11'h44c;
      end
      124'h85bec12b4b9a407894e45d4ae61ae1f: begin
        out = 4'ha;
      end
      70'h3635c9adc5dea1ae1f: begin
        out = 10'h3e9;
      end
      120'hd5fe01dedf5d2e885a0f34ae61ae1f: begin
        out = 10'h3e9;
      end
      120'hd5fe01dedf5cf85290616ecfc1ae1f: begin
        out = 1'h0;
      end
      120'hd5fe01dedf5cf85290616ecfd0f05f: begin
        out = 1'h0;
      end
      default: begin
        out = 19'h00000;
      end
    endcase
  end
endmodule
