/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [16-1:0] M_sixteen_bit_alu_out;
  wire [1-1:0] M_sixteen_bit_alu_z;
  wire [1-1:0] M_sixteen_bit_alu_v;
  wire [1-1:0] M_sixteen_bit_alu_n;
  reg [16-1:0] M_sixteen_bit_alu_a;
  reg [16-1:0] M_sixteen_bit_alu_b;
  reg [6-1:0] M_sixteen_bit_alu_alufn;
  alu_1 sixteen_bit_alu (
    .a(M_sixteen_bit_alu_a),
    .b(M_sixteen_bit_alu_b),
    .alufn(M_sixteen_bit_alu_alufn),
    .out(M_sixteen_bit_alu_out),
    .z(M_sixteen_bit_alu_z),
    .v(M_sixteen_bit_alu_v),
    .n(M_sixteen_bit_alu_n)
  );
  
  wire [19-1:0] M_rom_out;
  reg [38-1:0] M_rom_address;
  answer_rom_2 rom (
    .address(M_rom_address),
    .out(M_rom_out)
  );
  
  wire [16-1:0] M_btd_digits;
  reg [14-1:0] M_btd_value;
  bin_to_dec_3 btd (
    .value(M_btd_value),
    .digits(M_btd_digits)
  );
  
  localparam NUM_STATES = 7'h6e;
  
  localparam NUM_STATE_BITS = 3'h7;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_4 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_btn_cnd_out;
  reg [1-1:0] M_btn_cnd_in;
  button_conditioner_5 btn_cnd (
    .clk(clk),
    .in(M_btn_cnd_in),
    .out(M_btn_cnd_out)
  );
  wire [38-1:0] M_ans_out;
  reg [7-1:0] M_ans_in;
  answer_fsm_6 ans (
    .clk(clk),
    .rst(rst),
    .in(M_ans_in),
    .out(M_ans_out)
  );
  wire [7-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [16-1:0] M_seg_values;
  multi_seven_seg_7 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  wire [7-1:0] M_cnt_value;
  reg [1-1:0] M_cnt_clk;
  counter_8 cnt (
    .rst(rst),
    .clk(M_cnt_clk),
    .value(M_cnt_value)
  );
  
  always @* begin
    M_btn_cnd_in = io_button[0+0-:1];
    M_cnt_clk = clk & (!io_dip[16+7+0-:1] | M_btn_cnd_out);
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_ans_in = M_cnt_value;
    M_sixteen_bit_alu_a = M_ans_out[22+15-:16];
    M_sixteen_bit_alu_b = M_ans_out[6+15-:16];
    M_sixteen_bit_alu_alufn = M_ans_out[0+5-:6];
    M_rom_address = M_ans_out;
    io_led[16+5+2-:3] = {M_sixteen_bit_alu_z, M_sixteen_bit_alu_v, M_sixteen_bit_alu_n};
    io_led[16+2+2-:3] = {M_rom_out[2+0-:1], M_rom_out[1+0-:1], M_rom_out[0+0-:1]};
    io_led[0+15-:16] = M_sixteen_bit_alu_out;
    io_led[0+15-:16] = M_rom_out[3+15-:16];
    io_led[16+0+0-:1] = (((|(M_rom_out[3+15-:16] ^ M_sixteen_bit_alu_out))) | (M_rom_out[2+0-:1] ^ M_sixteen_bit_alu_z) | (M_rom_out[1+0-:1] ^ M_sixteen_bit_alu_v) | (M_rom_out[0+0-:1] ^ M_sixteen_bit_alu_n));
    M_btd_value = M_cnt_value;
    M_seg_values = M_btd_digits;
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
  end
endmodule
