/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module data_rom_16 (
    input [15:0] address,
    output reg [15:0] out
  );
  
  
  
  localparam DATA = 96'h001f000f000a001500050001;
  
  always @* begin
    out = DATA[(address >> 1'h1)*16+15-:16];
  end
endmodule
