/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module inst_mem_15 (
    input [15:0] ia,
    output reg [31:0] id
  );
  
  
  
  localparam INSTRUCTION = 416'h77fffff3631f0005631f0005631f0004631f0004631f0003631f0003631f0002631f0002631f0001631f0001631f0000631f0000;
  
  always @* begin
    id = INSTRUCTION[(ia >> 2'h2)*32+31-:32];
  end
endmodule
