/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module inst_mem_10 (
    input [15:0] ia,
    output reg [31:0] id
  );
  
  
  
  localparam INSTRUCTION = 128'h775ffffcb358c800c33f0002c31f0007;
  
  always @* begin
    id = INSTRUCTION[(ia >> 2'h2)*32+31-:32];
  end
endmodule
